# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SystemTray-Applet-Win32
version:      0.02
version_from: lib/SystemTray/Applet/Win32.pm
installdirs:  site
requires:
    SystemTray::Applet:            0
    Test::More:                    0
    Win32::GUI:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
